<?php

namespace ContainerM72fwEj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RvmMkcYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rvmMkcY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rvmMkcY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\TaskController::createAction' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\TaskController::deleteTaskAction' => ['privates', '.service_locator.5vYvvuC', 'get_ServiceLocator_5vYvvuCService', true],
            'App\\Controller\\TaskController::editAction' => ['privates', '.service_locator.5vYvvuC', 'get_ServiceLocator_5vYvvuCService', true],
            'App\\Controller\\TaskController::listAction' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\TaskController::toggleTaskAction' => ['privates', '.service_locator.5vYvvuC', 'get_ServiceLocator_5vYvvuCService', true],
            'App\\Controller\\UserController::createAction' => ['privates', '.service_locator.Dby0_1s', 'get_ServiceLocator_Dby01sService', true],
            'App\\Controller\\UserController::editAction' => ['privates', '.service_locator.WF25WwK', 'get_ServiceLocator_WF25WwKService', true],
            'App\\Controller\\UserController::listAction' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\TaskController:createAction' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\TaskController:deleteTaskAction' => ['privates', '.service_locator.5vYvvuC', 'get_ServiceLocator_5vYvvuCService', true],
            'App\\Controller\\TaskController:editAction' => ['privates', '.service_locator.5vYvvuC', 'get_ServiceLocator_5vYvvuCService', true],
            'App\\Controller\\TaskController:listAction' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\TaskController:toggleTaskAction' => ['privates', '.service_locator.5vYvvuC', 'get_ServiceLocator_5vYvvuCService', true],
            'App\\Controller\\UserController:createAction' => ['privates', '.service_locator.Dby0_1s', 'get_ServiceLocator_Dby01sService', true],
            'App\\Controller\\UserController:editAction' => ['privates', '.service_locator.WF25WwK', 'get_ServiceLocator_WF25WwKService', true],
            'App\\Controller\\UserController:listAction' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\TaskController::createAction' => '?',
            'App\\Controller\\TaskController::deleteTaskAction' => '?',
            'App\\Controller\\TaskController::editAction' => '?',
            'App\\Controller\\TaskController::listAction' => '?',
            'App\\Controller\\TaskController::toggleTaskAction' => '?',
            'App\\Controller\\UserController::createAction' => '?',
            'App\\Controller\\UserController::editAction' => '?',
            'App\\Controller\\UserController::listAction' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\TaskController:createAction' => '?',
            'App\\Controller\\TaskController:deleteTaskAction' => '?',
            'App\\Controller\\TaskController:editAction' => '?',
            'App\\Controller\\TaskController:listAction' => '?',
            'App\\Controller\\TaskController:toggleTaskAction' => '?',
            'App\\Controller\\UserController:createAction' => '?',
            'App\\Controller\\UserController:editAction' => '?',
            'App\\Controller\\UserController:listAction' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
