<?php

namespace ContainerM72fwEj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5vYvvuCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5vYvvuC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5vYvvuC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'task' => ['privates', '.errored..service_locator.5vYvvuC.App\\Entity\\Task', NULL, 'Cannot autowire service ".service_locator.5vYvvuC": it references class "App\\Entity\\Task" but no such service exists.'],
        ], [
            'doctrine' => '?',
            'task' => 'App\\Entity\\Task',
        ]);
    }
}
