<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP6xyA20\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP6xyA20/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP6xyA20.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP6xyA20\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerP6xyA20\App_KernelDevDebugContainer([
    'container.build_hash' => 'P6xyA20',
    'container.build_id' => 'd8a56ae2',
    'container.build_time' => 1668597674,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP6xyA20');
