<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM72fwEj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM72fwEj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM72fwEj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM72fwEj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerM72fwEj\App_KernelDevDebugContainer([
    'container.build_hash' => 'M72fwEj',
    'container.build_id' => '375c8579',
    'container.build_time' => 1668092841,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM72fwEj');
